/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg19130535_javamail;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author ivan_
 * IVAN HERRERA GARCIA 
 * 19130535
 * ULT MOD 05/03/2021
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    //SE CREAN VARIABLES
    //PAR ES DE TIPO INICIO (JFRAME)
    Inicio par;
    //RUTA ES DE TIPO STRING
    String ruta;
    //ARC ES DE TIPO STRING
    String arc;
    //SE MANDA UN PARAMETRO A LA CLASE PANEL DE TIPO JFRAME
    public Panel(Inicio jframe) {
        initComponents();
        //SE INICIALIZA PAR CON UN OBJETO DE TIPO JFRAME
        par=jframe;
        //A LA ETIQUETA USUARIO SE LE COLOCA EL CONTENIDO DEL JTEXTBOX USADO EN EL JFRAME PANEL
        usuario.setText(par.mail.getText());
        //SE COLOCA A LA ETIQUETA ADJUNTO LA INFORMACION "SIN ARCHIVOS"
        adjunto.setText("Sin archivos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtrecibe = new javax.swing.JTextField();
        txtasunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmensaje = new javax.swing.JTextArea();
        enviar_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adjuntar_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        adjunto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtrecibe, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 30, 182, -1));
        getContentPane().add(txtasunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 56, 182, -1));

        txtmensaje.setColumns(20);
        txtmensaje.setRows(5);
        jScrollPane1.setViewportView(txtmensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 82, 182, -1));

        enviar_btn.setText("Enviar");
        enviar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(enviar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, 80, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Destinatario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Asunto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mensaje");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        adjuntar_btn.setText("Adjuntar");
        adjuntar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjuntar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(adjuntar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, 80, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Nombre");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 5, -1, -1));

        adjunto.setForeground(new java.awt.Color(255, 255, 255));
        adjunto.setText("adj");
        getContentPane().add(adjunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg19130535_javamail/fondo_2.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 240));

        jMenu1.setText("Cerrar sesion");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenu3.setText("Ejemplo");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_btnActionPerformed
        // TODO add your handling code here:
  
        //SE VALIDA EL JTEXTBOX 
        if ("".equals(txtrecibe.getText())) {
            //SI NO HAY CONTENIDO EN EL JTEXTBOX NO SE ENVIARA NINGUN CORREO
            JOptionPane.showMessageDialog(null, "No hay destinatario", "Infomacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
        //SE CREA UN OBJETO DE TIPO PROPIERTIES
        Properties propiedad = new Properties();
        //SE COLOCAN PROPIEDADES PARA EL FUNCIONAMIENTO Y PODER ENLAZARCE CON GOOGLE (GMAIL)
        propiedad.setProperty("mail.smtp.host", "smtp.gmail.com");
        propiedad.setProperty("mail.smtp.starttls.enable", "true");
        propiedad.setProperty("mail.smtp.port", "587");
        
       //SE CREA UN OBJETO DEL TIPO SESSION
        Session sesion= Session.getDefaultInstance(propiedad);
        
        //SE CREAN Y COLOCAN VARIABLES DEL TIPO STRING CON LOS JTEXTBOX DEL JFRAME
        //SE COLOCA EL CONTENIDO DEL JTEXTBOX CORREO DEL JFRAME (INICIO)
        String correoEnvia= par.mail.getText();
        //SE COLOCA EL CONTENIDO DEL JPASSWORD CONTRASENA DEL JFRAME (INICIO)
        String contrasena=par.password.getText();
        //SE COLOCA EL CONTENIDO DEL JTEXTBOX TXTRECIBE
        String destinatario=txtrecibe.getText();
        //SE COLOCA EL CONTENIDO DEL JTEXTBOX TXTASUNTO
        String asunto=txtasunto.getText();
        //SE COLOCA EL CONTENIDO DEL JTEXTBOX TXTMENSAJE
        String mensaje=txtmensaje.getText();
         
        //SE CREA UN OBJETO DEL TIPO MIMEMESSAGE CON EL PARAMETRO DE SESION
        MimeMessage mail = new MimeMessage(sesion);

        //SE CREA UN OBJETO DEL TIPO BODYPART 
        BodyPart adjunto = new MimeBodyPart();
        try {
                //SE COLOCA AL OBJETO ADJUNTO LA RUTA DE UN ARCHIVO USANDO FILEDATASOURCE
                adjunto.setDataHandler(new DataHandler(new FileDataSource(ruta)));
                //SE COLOCA NOMBRE AL ARCHIVO
                adjunto.setFileName(ruta);
            } catch (MessagingException ex) {
                //EN CASO DE UN ERROR SE MANDARA UN MENSAJE EN LA CONSOLA
                Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
            }

        //SE CREA UN OBJETO DEL TIPO MIMEMULTIPART
        MimeMultipart multiParte = new MimeMultipart();


        try {
                //SE AGREGA UN CONTENIDO AL OBJETO MULTIPARTE, EL CUAL ES DEL TIPO BODYPART
                multiParte.addBodyPart(adjunto);
            } catch (MessagingException ex) {
                //EN CASO DE UN ERROR SE MANDARA UN MENSAJE EN LA CONSOLA
                Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        try {
            //SE LE COLOCA CONTENIDO AL OBJETO MAIL
            //SE LE COLOCA EL CORREO QUE ENVIARA EL CORREO ELECTRONICO
            mail.setFrom(new InternetAddress(correoEnvia));
            //SE AGREGA EL CORREO QUE DEBERA RECIBIR EL CORREO ELECTRONICO
            mail.addRecipient(Message.RecipientType.TO, new InternetAddress(destinatario));
            //SE AGREGA EL ASUNTO DEL CORREO ELECTRONICO ANTERIORMENTE GUARDADO EN UNA VARIABLE (ASUNTO)
            mail.setSubject(asunto);
            //SE AGREGA EL MENSAJE DEL CORREO ELECTRONICO ANTERIORMENTE GUARDADO EN UNA VARIABLE (MENSAJE)
            mail.setText(mensaje);
            //SE COLOCA EL CONTENIDO DEL OBJETO MULTIPARTE EN EL OBJETO MAIL
            mail.setContent(multiParte);
            
            //SE CREA UN OBJETO TRANSPORT PARA PODER ENVIAR LOS DATOS COMO UN CORREO ELECTRONICO
            //SE INICIALIZA EL OBJETO CON EL OBJETO SESION
            Transport transporte = sesion.getTransport("smtp");
            //SE CONECTA EL OBJETO TRANSPORTE CON GMAIL PARA REVISAR SI EXISTE LA CUENTA A USAR
            transporte.connect(correoEnvia,contrasena);
            //SE ENVIA EL CORREO ELECTRONICO
            transporte.sendMessage(mail, mail.getRecipients(Message.RecipientType.TO));
            //SE CIERRA LA CONEXION CON GMAIL
            transporte.close();
            //PARA MAYOR SEGURIDAD SE MANDA UN MENSAJE VISUAL COMO CONFIRMACION
            JOptionPane.showMessageDialog(null, "Correo enviado");
        } catch (AddressException ex) {
            //EN CASO DE UN ERROR SE MANDARA UN MENSAJE EN LA CONSOLA
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            //EN CASO DE UN ERROR SE MANDARA UN MENSAJE EN LA CONSOLA
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_enviar_btnActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        //SE OCULTA EL JFRAME (PANEL)
        this.setVisible(false);
        //SE HACE VISIBLE EL JFRAME (INICIO)
        par.setVisible(true);
        //SE COLOCA LA INFORMACION EN EL JTEXTOBOX CORREO DEL JFRAME (INICIO)
        par.mail.setText("");
        //SE COLOCA LA INFORMACION EN EL JPASSWORD PASSWORD DEL JFRAME (INICIO)
        par.password.setText("");
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void adjuntar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjuntar_btnActionPerformed
        // TODO add your handling code here:
        //SE CREA UN OBJETO DEL TIPO JFILECHOOSER
        JFileChooser fileChooser = new JFileChooser();
        //SE ABRE UNA VENTANA EN EL CUAL SE PODRA ELEGIR EL ARCHIVO A ENVIAR
        fileChooser.showOpenDialog(fileChooser);
        try {
            //SE GUARDA LA RUTA DEL ARCHIVO
            ruta = fileChooser.getSelectedFile().getAbsolutePath(); 
            //SE GUARDA EL NOMBRE DEL ARCHIVO
            arc="Archivo: "+fileChooser.getSelectedFile().getName();
            //arc= fileChooser.getSize().toString()+" "+arc;
            //SE COLOCA EN LA ETIQUETA ADJUNTO EL NOMBRE DEL ARCHIVO CON LA VARIABLE ARC
            adjunto.setText(arc);
        } catch (Exception e) {
            //EN CASO DE UN ERROR SE MANDARA UN MENSAJE EN LA CONSOLA
            System.out.println("No se ha seleccionado ningún fichero");
        }
           
        
    }//GEN-LAST:event_adjuntar_btnActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        //COMO EJEMPLO SE COLOCARA LA SIGUENTE INFORMACION EN LOS JTEXTBOX TXTRECIBE, TXTASUNTO Y TXTMENSAJE
        txtrecibe.setText("herreraleon14@gmail.com");
        txtasunto.setText("EJEMPLO");
        txtmensaje.setText("Ejemplo de un correo electronico");
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel(new Inicio()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adjuntar_btn;
    private javax.swing.JLabel adjunto;
    private javax.swing.JButton enviar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtasunto;
    private javax.swing.JTextArea txtmensaje;
    private javax.swing.JTextField txtrecibe;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
